#include <iostream>

int main(int argc, const char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: sysy_formatter <input-file>" << std::endl;
        return 1;
    }
    // TODO: You need to call the lexer and parser generated by ANTLR4,
    // and invoke the visit method in your own implemented Visitor.
    
    return 0;
}